#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		setMotor(motorB, 35);
		setMotor(motorC, 35);

			delay(3500);

				setMotor(motorA, -200);


		setMotor(motorB,-35);
		setMotor(motorC,-35);

			delay(3500);



}
