#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	if(getColorName(S3)== colorBrown || getColorName(S3)== colorGreen)
		{

				motor[leftMotor]=75;
				motor[rightMotor]=0;
				delay(490);

					motor[leftMotor]=0;
					motor[rightMotor]=0;


			}

				else{
						motor[leftMotor]=0;
						motor[rightMotor]=75;
						delay(490);
						motor[leftMotor]=0;
						motor[rightMotor]=0;

		}
}
