#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{ setMotor(motorB, 75);
	setMotor(motorC, 75);

		waitUntil(getTouchValue(touchSensor)==1);
		setMotor(motorB, 0);
		setMotor(motorC, 0);



}
