#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{	int i=0;
		while(i<5){
					motor[leftMotor]=75;
					motor[rightMotor]=75;
					delay(500);
						motor[leftMotor]=-75;
						motor[rightMotor]=-75;
						delay(400);
						i++;

	}



}
