#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		setMotor(motorB, 55);
		setMotor(motorC, 55);
			delay(1000);
		setMotor(motorB, 0);
		setMotor(motorC, 0);

				setMotor(motorA, -60);
					delay(1000);
				setMotor(motorA, 60);
					delay(1000);

		setMotor(motorB, 55);
		setMotor(motorC, 55);
			delay(1500);
		setMotor(motorB, 0);
		setMotor(motorC, 0);

				setMotor(motorA, -60);
					delay(1000);
				setMotor(motorA, 60);
					delay(1000);

				setMotor(motorB, 55);
				setMotor(motorC, 55);
					delay(1500);
				setMotor(motorB, 0);
				setMotor(motorC, 0);

				setMotor(motorA, -60);
						delay(1000);
				setMotor(motorA, 60);

			delay(1000);

		setMotor(motorB,-55);
		setMotor(motorC,-55);

			delay(4500);
		setMotor(motorB, 0);
		setMotor(motorC, 0);


}
