#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever){
			motor[leftMotor]=75;
			motor[rightMotor]=75;
				delay(3000);
						motor[leftMotor]=75;
						motor[rightMotor]=0;
						delay(400);

					}



}
