#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 75;
	motor[motorC] = 0;
	waitUntil(getGyroDegrees (gyroSensor) > 90);



}
