#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	for (int i=0; i == getTouchValue(S1);){

				motor[motorB] = 75;
				motor[motorC] = 75;

	}

		motor[motorB] = -50;
		motor[motorC] = -50;
			delay(1000);

		motor[motorB] = 75;
		motor[motorC] = 0;
			delay(500);

for (int i=0; i == getTouchValue(S1);){

				motor[motorB] = 75;
				motor[motorC] = 75;

	}

		motor[motorB] = -50;
		motor[motorC] = -50;
			delay(1000);

		motor[motorB] = 75;
		motor[motorC] = 0;
			delay(500);


		for (int i=0; i == getTouchValue(S1);){

				motor[motorB] = 75;
				motor[motorC] = 75;

	}

		motor[motorB] = -50;
		motor[motorC] = -50;
			delay(1000);

		motor[motorB] = 75;
		motor[motorC] = 0;
			delay(500);

		for (int i=0; i == getTouchValue(S1);){

				motor[motorB] = 75;
				motor[motorC] = 75;

	}

		motor[motorB] = -50;
		motor[motorC] = -50;
			delay(1000);

		motor[motorB] = 75;
		motor[motorC] = 0;
			delay(500);










}
